### ISSUE TITLE
Create a delete function.

### ISSUE THREAD

**Issue by PritKalariya** [PritKalariya/Data-Structure-Programs-Algorithms#7]
Try creating a **simple** `delete function` for **_Binary Search Tree_** by using the given code and properly understanding the flow of the program. Try to keep the steps simple so that it would be easy to understand. 

_Thank you!_

**Comment by kambleaa007** [comment]
sure, deleting node means, simply, making address points to NULL, so you wont traverse node again,
think which node you want to delete, (need input), 
travel till Node found, 
deleting node have 3 conditions,
node with left node, right node, no children node (alone),

**Comment by PritKalariya** [comment]
Yes! That's helpful. The first challenge is to traverse till that particular element you want to delete. How can i do that ?

**Comment by ghost** [comment]
I have made pull request. You can verify code. If have any doubt DM me on twitter @sskenjale
